name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Node V20 
      uses: actions/setup-node@v3
      with:
        node-version: 20.x 
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install

    - name: Add Prisma Types
      run: pnpm exec prisma generate

    - name: Lint Project
      run:  pnpm lint

    - name: Type Check Project
      run:  pnpm typecheck

